In [1]:
pip install numpy 

In [2]:
install numpy as np

SyntaxError: invalid syntax (42992965.py, line 1)

In [3]:
import numpy as np

In [9]:
np.arranges(10)

AttributeError: module 'numpy' has no attribute 'arranges'

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3,8)

array([3, 4, 5, 6, 7])

In [12]:
np.arrange(2,18,3)

AttributeError: module 'numpy' has no attribute 'arrange'

In [14]:
np.arange(2,17,3)

array([ 2,  5,  8, 11, 14])

In [16]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [26]:
c=np.array([[1,2,3],[4,5,6]])
c.shape

(2, 3)

In [27]:
c.size

6

In [28]:
c.edim

AttributeError: 'numpy.ndarray' object has no attribute 'edim'

In [31]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
a.shape

(20,)

In [33]:
b=a.reshape(4,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
x=np.arange(1,21).reshape(4,5)
x


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [36]:
x.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [37]:
np.flip(x,axis=0)

array([[16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [38]:
np.ones(25).reshape(5,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
d=np.array([[1,2,3,4],[5,6,7,8]])
d.sum()

np.int64(36)